mutation createNewLesson {
  createLesson(
    createLessonInput: {
      name: "Economics Class"
      startDate: "2020-05-09T18:00:00Z"
      endDate: "2020-05-09T18:30:00Z"
    }
  ) {
    id
    name
    startDate
    endDate
  }
}
